apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
spec:
  selector:
    app: {{ .Release.Name }}-gateway
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4000
